version: 1.0.{build}
image: Visual Studio 2019
environment:
  access_token: 
    secure: XObFm6kvn4ywvuntr9WHP9Y8c9HgFpRafNvIpwr2LjKnH3xauP05OI8XC0F/fsK8
install:
- ps: Install-Module -Name FXPSYaml -Force
build_script:
- ps: >-
    foreach ($yamlfile in (Get-ChildItem *.yaml))

    {
        $yaml = ConvertFrom-Yaml -Path $yamlfile.FullName

        $sb = [System.Text.StringBuilder]::new()

        [void]$sb.AppendLine('<html>')
        [void]$sb.AppendLine('    <head>')
        [void]$sb.AppendLine('        <style>')
        [void]$sb.AppendLine('            table {')
        [void]$sb.AppendLine('                width: 60%;')
        [void]$sb.AppendLine('                margin: 0 auto;')
        [void]$sb.AppendLine('                background-color: #000000;')
        [void]$sb.AppendLine('            }')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('            th {')
        [void]$sb.AppendLine('                background-color: #DCDCDC;')
        [void]$sb.AppendLine('            }')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('            table,')
        [void]$sb.AppendLine('            th,')
        [void]$sb.AppendLine('            td {')
        [void]$sb.AppendLine('                border: 3px solid black;')
        [void]$sb.AppendLine('                border-collapse: collapse;')
        [void]$sb.AppendLine('                font-weight: bold;')
        [void]$sb.AppendLine('            }')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('            th,')
        [void]$sb.AppendLine('            td {')
        [void]$sb.AppendLine('                padding: 15px;')
        [void]$sb.AppendLine('                text-align: center;')
        [void]$sb.AppendLine('            }')
        [void]$sb.AppendLine('        </style>')
        [void]$sb.AppendLine('     </head>')
        [void]$sb.AppendLine('     <body>')
        [void]$sb.AppendLine('         <table>')
        [void]$sb.AppendLine('             <tr>')
        [void]$sb.AppendLine("                 <th colspan=`"$($yaml.header.colspan)`" id=`"th01`">$($yaml.header.name)</th>")
        [void]$sb.AppendLine('             </tr>')

        foreach($row in $yaml.rows)
        {
            [void]$sb.AppendLine('            <tr>')
            [void]$sb.AppendLine("                <td style=`"background-color: #FFFFFF`">$($row.name)</td>")

            $red = [string]::Format("{0:X2}", $row.style.red)
            $green = [string]::Format("{0:X2}", $row.style.green)
            $blue = [string]::Format("{0:X2}", $row.style.blue)
            $backgroundcolor = "$($red)$($green)$($blue)"

            foreach($entry in $row.entries)
            {
                [void]$sb.AppendLine("                <td colspan=$($entry.attributes.colspan) style=`"background-color: #$($backgroundcolor)`">$($entry.name)</td>")
            }

            [void]$sb.AppendLine('            </tr>')
        }

        [void]$sb.AppendLine('        </table>')
        [void]$sb.AppendLine('    </body>')
        [void]$sb.AppendLine('</html>')

        if(-not (Test-Path .\Maps))
        {
            mkdir .\Maps
        }

        $sb.ToString() | Out-File -FilePath ".\Maps\$($yamlfile.Name.Split('.')[0]).html"
    }
artifacts:
- path: Maps\*.html
on_success:
  - git config --global credential.helper store
  - ps: |
      $accesstoken = ($env:access_token.Split(': ')[2])
  - ps: Add-Content -Path "$HOME\.git-credentials" -Value "https://$($accesstoken):x-oauth-basic@github.com`n" -NoNewline
  - ps: cat "$HOME\.git-credentials"
  - git config --global user.email "jared@invoke-ir.com"
  - git config --global user.name "jaredcatkinson"
  - git remote -v
  - git add Maps/
  - git commit -m "[skip appveyor] Appveyor adding generated html files"
  - git push origin master --force
